copy SoarIMPRINTPlugin\bin\debug\SoarIMPRINTPlugin.dll "C:\Users\christopher.j.best2\Desktop\IMPRINT Pro 3.1\"
copy Utility\bin\debug\Utility.dll "C:\Users\christopher.j.best2\Desktop\IMPRINT Pro 3.1\"
copy SMLExtension\bin\debug\SMLExtension.dll "C:\Users\christopher.j.best2\Desktop\IMPRINT Pro 3.1\"
xcopy /E /Y ..\TestAgent\* "C:\Users\christopher.j.best2\Desktop\IMPRINT Pro 3.1\Scope\agent\"
xcopy /E /Y ..\ScopeAgent\* "C:\Users\christopher.j.best2\Desktop\IMPRINT Pro 3.1\Scope\agent\"